### ISSUE TITLE
Index is always highlighted as the active page.

### ISSUE THREAD

**Issue by rctillotson25** [GavickPro/Portfolio-Free-Ghost-Theme#11]
No matter which page I'm on, the index always has the menu__active class on it. Maybe write a JS function that checks the URL?

**Comment by rctillotson25** [comment]
I fixed this issue in the latest commit that has been submitted as a pull request. If you have any questions, let me know!  Feel free to close this if you feel comfortable with the changes. Otherwise, I'll just keep going on my fork.  This is a great project!

**Comment by unwitting** [comment]
I think you'll be looking to carry on with your fork - I'll probably switch to using your fork too :) see the issue #5 that I suggested a JS fix on for the same problem, creator isn't amenable to putting it in.

**Comment by rctillotson25** [comment]
Oh - interesting. I didn't see that. I assumed it was just something that hadn't been done yet. Yeah, I'll continue work on my fork then. Feel free to contribute - I'm probably going to change out some of the icons in favor of either icono or fontawesome.

**Comment by rctillotson25** [comment]
I'll leave this open in case the original repo creator wants to comment on this issue.

**Comment by dziudek** [comment]
Issue is solved with the new {{navigation}} helper added in Ghost 0.5.9 - support is available in the newly released v.1.3.0 of the Portfolio theme.
