### ISSUE TITLE
featured-image

### ISSUE THREAD

**Issue by trickkiste** [GavickPro/Portfolio-Free-Ghost-Theme#13]
The whole featured-image functionality does not seem to be working anymore in v1.2.2. This also concerns the part, which applies this special post image style to the first occurance of "p > img".

**Comment by dziudek** [comment]
Hello,

Did you remember that new versions of Ghosts contains built-in featured image feature?

**Comment by trickkiste** [comment]
Did not know that. Thanks for the hint.
