### ISSUE TITLE
Title on the Image

### ISSUE THREAD

**Issue by IamSachin** [GavickPro/Portfolio-Free-Ghost-Theme#16]
Is there any way of showing the title over the post image?
Something like this:
![pangot_git](https://cloud.githubusercontent.com/assets/1570826/7818166/a44f43d2-03f7-11e5-9f14-946c3b6d287a.png)

**Comment by dziudek** [comment]
Hello,

I'm sorry but it is a custom work beyond of our technical support.

**Comment by qLb** [comment]
i wld try some tool like pablo for preparing my post covers if i were you. buffer's pablo - http://bit.ly/1OBJMU4                                                                                                                                                                                                                                                                                                                                        qL.b                                                                                                                                                                                                                From: Sachin RajputSent: wtorek, 26 maja 2015 19:06To: GavickPro/Portfolio-Free-Ghost-ThemeReply To: GavickPro/Portfolio-Free-Ghost-ThemeSubject: [Portfolio-Free-Ghost-Theme] Title on the Image (#16)Is there any way of showing the title over the post image?
Something like this:


—Reply to this email directly or view it on GitHub.
