### ISSUE TITLE
Videos not being responsive

### ISSUE THREAD

**Issue by IamSachin** [GavickPro/Portfolio-Free-Ghost-Theme#17]
Hi guys,
For some reason, the videos that I am embedding are not being responsive. Here is a link to an entry
http://www.foodietraveler.in/chicken-spring/

Please suggest what I could be doing wrong

Regards

**Comment by dziudek** [comment]
You're right - please apply the following patch: https://github.com/GavickPro/Portfolio-Free-Ghost-Theme/commit/1a3a938a8313a654ac9d9ef40c5c6e27d86408fa
